twk_backend/twk_backend/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf.urls import include

import twk_auth.views
import twk_save.views
import twk_backend.views
import twk_load.views
import twk_submit.views
import twk_send.views

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', RedirectView.as_view(url = '/login/')),
    url(r'^login$', RedirectView.as_view(url = '/login/')),
    url(r'^login/$', twk_auth.views.login),
    url(r'^save_hw$', RedirectView.as_view(url = '/save_hw/')),
    url(r'^save_hw/?$', twk_save.views.save_hw),
    url(r'^load_hw$', RedirectView.as_view(url = '/load_hw/')),
    url(r'^load_hw/?$', twk_load.views.load_hw),
    url(r'^submit_hw$', RedirectView.as_view(url = '/submit_hw/')),
    url(r'^submit_hw/?$', twk_submit.views.submit_hw),
    url(r'^revise_hw$', RedirectView.as_view(url = '/revise_hw/')),
    url(r'^revise_hw/?$', twk_submit.views.revise_hw),
    url(r'^view_peer_review_results$', RedirectView.as_view(url = '/view_peer_review_results/')),
    url(r'^view_peer_review_results/?$', twk_submit.views.view_peer_review_results),
    url(r'get_code/(?P<id>[-\w]+)/', twk_submit.views.get_code),
    url(r'^publish_hw/(?P<id>[-\w]+)/', twk_save.views.load_publish_hw),
    url(r'^publish_hw/', twk_save.views.save_publish_hw),
    url(r'^peer_review_task_dispatch$', RedirectView.as_view(url='/peer_review_task_dispatch/')),
    url(r'^peer_review_task_dispatch/?$', twk_send.views.peer_review_task_dispatch),
    url(r'^isLogined$', RedirectView.as_view(url = '/isLogined/')),
    url(r'^isLogined/$', twk_auth.views.isLogined),
    url(r'^logout/$', twk_auth.views.logout),
    url('admin/', admin.site.urls),
    url(r'^templates/js/ide.js$', twk_backend.views.js_ide_js),
    url(r'^templates/ide.html$', twk_backend.views.ide_html),
    url(r'^templates/upload.html$', twk_backend.views.upload_html),
    url(r'^templates/user$', twk_backend.views.user_html),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

twk_backend/twk_save/models.py
from django.db import models
from django.contrib.auth.models import User

class SavedHW(models.Model):
    source_code = models.TextField()
    stdin = models.TextField()
    language_id = models.TextField()
    file_name = models.TextField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.user) + "'s hw" + str(self.file_name) 

class PublishHW(models.Model):
    question = models.TextField()
    stdin = models.TextField()
    stdout = models.TextField()
    language_id = models.TextField()
    def __str__(self):
        return str(self.question)

twk_backend/templates/ide.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="description" content="Online compiler and IDE powered by Judge0 API">
  <meta name="keywords" content="online compiler, online ide">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>

  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
  <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">

  <link rel="stylesheet" href="../static/css/codemirror.css">
  <script src="../static/js/codemirror.js"></script>
  <script src="../static/js/mode/simple.js"></script>
  <script src="../static/js/mode/clike.js"></script>
  <script src="../static/js/mode/clojure.js"></script>
  <script src="../static/js/mode/crystal.js"></script>
  <script src="../static/js/mode/elixir.js"></script>
  <script src="../static/js/mode/erlang.js"></script>
  <script src="../static/js/mode/go.js"></script>
  <script src="../static/js/mode/haskell.js"></script>
  <script src="../static/js/mode/javascript.js"></script>
  <script src="../static/js/mode/mllike.js"></script>
  <script src="../static/js/mode/octave.js"></script>
  <script src="../static/js/mode/pascal.js"></script>
  <script src="../static/js/mode/python.js"></script>
  <script src="../static/js/mode/ruby.js"></script>
  <script src="../static/js/mode/rust.js"></script>
  <script src="../static/js/mode/shell.js"></script>

  <script src="../static/js/download.js"></script>

  <link rel="stylesheet" href="../static/css/addon/dialog.css">

  <script src="../static/js/addon/searchcursor.js"></script>
  <script src="../static/js/addon/search.js"></script>
  <script src="../static/js/addon/dialog.js"></script>
  <script src="../static/js/addon/matchbrackets.js"></script>
  <script src="../static/js/addon/closebrackets.js"></script>

  <script src="../static/js/keymap/vim.js"></script>

  <link rel="stylesheet" href="../static/css/ide.css">
  <script src="js/ide.js"></script>

  <title>TWK IDE</title>
  <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
  <link rel="icon" href="./favicon.ico" type="image/x-icon">
</head>

<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div id="mySidenav" class="sidenav">
            <a href="#" class="closebtn"  align="left">{{User}}</a>
            <a href="#">Account</a>
            <a href="#">Assignments</a>
            {{add_new|safe|escape }}
            {{peer_review|safe|escape }}
            <a href="{{TWK_URL}}/view_peer_review_results">View peer review results</a>
            <a href="{{TWK_URL}}/logout">Sign out</a>
          </div>
      <div class="navbar-header">
          <a id="navBtn" class="navbar-brand" style="font-size:30px;cursor:pointer;color:white;" onclick="openNav()">
              &#9776;
              
            </a>
            <a class="navbar-brand"><small>{{User}}</small></a>
      </div>
      <span id = "judging" disabled>judging</span>
      <div id = "judgement" style="display: none;margin-left: 20px;">
        <div id="true" style="width: 200px;justify-content: center;line-height: 50px;cursor: pointer;">
          <span style="color:yellow">Good</span>
          <span class="glyphicon glyphicon-ok" id="true" style="font-size: 40px;color:red;justify-content: center"></span>
        </div>
        <div id="false" style="width: 200px;justify-content: center;line-height: 50px;cursor: pointer;">
          <span style="color:yellow">Bad</span>
          <span class="glyphicon glyphicon-remove" id="true" style="font-size: 40px;color:red;justify-content: center"></span>
        </div>
        <textarea id="feedback" class="form-control" aria-label="With textarea" placeholder="input your feedback"></textarea>
      </div>
      <div class="navbar-form navbar-right">
        <select class="form-control" id="selectTaskBtn">
            {% for publish_hw in publish_hws %}
              <option value="{{publish_hw.id}}" mode="text/x-sh">Assignment {{ publish_hw.id }}</option>
            {% endfor %}
           
        </select>
        <button class="btn btn-danger" id="submitBtn" data-loading-text="Submitting...">
          <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Submit (Ctrl+Enter)
        </button>
        <div class="input-group">

          <select class="form-control" id="selectLanguageBtn">
            <option value="1" mode="text/x-sh">Bash (4.4)</option>
            <option value="2" mode="text/x-sh">Bash (4.0)</option>
            <option value="3" mode="text/x-pascal">Basic (fbc 1.05.0)</option>
            <option value="4" mode="text/x-csrc">C (gcc 7.2.0)</option>
            <option value="5" mode="text/x-csrc">C (gcc 6.4.0)</option>
            <option value="6" mode="text/x-csrc">C (gcc 6.3.0)</option>
            <option value="7" mode="text/x-csrc">C (gcc 5.4.0)</option>
            <option value="8" mode="text/x-csrc">C (gcc 4.9.4)</option>
            <option value="9" mode="text/x-csrc">C (gcc 4.8.5)</option>
            <option value="10" mode="text/x-c++src">C++ (g++ 7.2.0)</option>
            <option value="11" mode="text/x-c++src">C++ (g++ 6.4.0)</option>
            <option value="12" mode="text/x-c++src">C++ (g++ 6.3.0)</option>
            <option value="13" mode="text/x-c++src">C++ (g++ 5.4.0)</option>
            <option value="14" mode="text/x-c++src">C++ (g++ 4.9.4)</option>
            <option value="15" mode="text/x-c++src">C++ (g++ 4.8.5)</option>
            <option value="16" mode="text/x-csharp">C# (mono 5.4.0.167)</option>
            <option value="17" mode="text/x-csharp">C# (mono 5.2.0.224)</option>
            <option value="18" mode="text/x-clojure">Clojure (1.8.0)</option>
            <option value="19" mode="text/x-crystal">Crystal (0.23.1)</option>
            <option value="20" mode="text/x-elixir">Elixir (1.5.1)</option>
            <option value="21" mode="text/x-erlang">Erlang (OTP 20.0)</option>
            <option value="22" mode="text/x-go">Go (1.9)</option>
            <option value="23" mode="text/x-haskell">Haskell (ghc 8.2.1)</option>
            <option value="24" mode="text/x-haskell">Haskell (ghc 8.0.2)</option>
            <option value="25" mode="text/plain">Insect (5.0.0)</option>
            <option value="26" mode="text/x-java">Java (OpenJDK 9 with Eclipse OpenJ9)</option>
            <option value="27" mode="text/x-java">Java (OpenJDK 8)</option>
            <option value="28" mode="text/x-java">Java (OpenJDK 7)</option>
            <option value="29" mode="text/javascript">JavaScript (nodejs 8.5.0)</option>
            <option value="30" mode="text/javascript">JavaScript (nodejs 7.10.1)</option>
            <option value="31" mode="text/x-ocaml">OCaml (4.05.0)</option>
            <option value="32" mode="text/x-octave">Octave (4.2.0)</option>
            <option value="33" mode="text/x-pascal">Pascal (fpc 3.0.0)</option>
            <option value="34" mode="text/x-python">Python (3.6.0)</option>
            <option value="35" mode="text/x-python">Python (3.5.3)</option>
            <option value="36" mode="text/x-python">Python (2.7.9)</option>
            <option value="37" mode="text/x-python">Python (2.6.9)</option>
            <option value="38" mode="text/x-ruby">Ruby (2.4.0)</option>
            <option value="39" mode="text/x-ruby">Ruby (2.3.3)</option>
            <option value="40" mode="text/x-ruby">Ruby (2.2.6)</option>
            <option value="41" mode="text/x-ruby">Ruby (2.1.9)</option>
            <option value="42" mode="text/x-rustsrc">Rust (1.20.0)</option>
            <option value="43" mode="text/plain">Text (plain text)</option>
          </select>
        </div>
        <button class="btn btn-success" id="runBtn" data-loading-text="Running...">
            <span class="glyphicon glyphicon-play" aria-hidden="true"></span> Run (F9)
          </button>
        <button class="btn btn-warning" id="chatBtn" data-loading-text="Opening...">
          <h4 style="color:red;position: absolute;z-index: 10;margin-top: -10px;">{{count}}</h4>
          <span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span> Chat
        </button>

        <button class="btn btn-info" id="loadBtn" data-loading-text="Loading...">
            <span class="	glyphicon glyphicon-file" aria-hidden="true"></span> Load
          </button>
        <button class="btn btn-primary" id="saveBtn" data-loading-text="Saving...">
          <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Save to clould (Ctrl+S)
        </button>
        <button class="btn btn-default" id="downloadSourceBtn" data-toggle="tooltip" data-placement="bottom" title="Download source">
          <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        </button>
        <div class="vertical-spacer"></div>
        <input type="checkbox" id="vimCheckBox" data-toggle="toggle" data-on="Vim Mode On" data-off="Vim Mode Off" data-onstyle="success">
      </div>
    </div>
  </nav>
  <iframe id="myiframe" style="border: 0; width: 100%; height:500px;display:none; width: 1680px; height: 640px" src="{{ rocket_chat_url }}/channel/general">
  </iframe>
  <div id="sourceEditor"></div>
  <div class="container-fluid">
    <div class="row labels">
      <div id="inputLabel" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h4>
          <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Input
          <small>optional</small>
          <button class="btn btn-default pull-right" id="downloadInputBtn" data-toggle="tooltip" data-placement="top" title="Download input">
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
          </button>
        </h4>
      </div>
      <div id="outputLabel" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h4>
          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Output
          <small id="emptyIndicator">empty</small>
          <button class="btn btn-default pull-right" id="downloadOutputBtn" data-toggle="tooltip" data-placement="top" title="Download output">
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
          </button>
          <small class="pull-right" id="statusLine"></small>
        </h4>
      </div>
    </div>
    <div class="row ioEditors">
      <div id="inputEditor" class="col-xs-6 col-sm-6 col-md-6 col-lg-6"></div>
      <div id="outputEditor" class="col-xs-6 col-sm-6 col-md-6 col-lg-6"></div>
    </div>
    
      <div class="row">
        <div id="footer" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <p>
            © 2018 <a href="https://sites.google.com/site/tungweikuo/">TWK IDE</a>,
            Powered by <a href="https://api.judge0.com">Judge0 API</a>,
            Available on <a href="https://github.com/judge0/ide">GitHub</a>
          </p>
        </div>
      </div>
   
  </div>
</body>

</html>

twk_backend/templates/upload.html
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Upload</title>
    <link rel="stylesheet" href="../static/css/upload.css">
</head>
{% if user.is_authenticated %}
{% if not user.is_staff %}
<h3>Not allowed to access this page</h3>
{% else %}
{% block content %}

<body>
    <div id="content" class="colM">

        <h1>Upload hw</h1>
        <div id="content-main">

            <div>
                <fieldset class="module aligned ">
                    <!-- <div class="form-row field-source_code">
                                    <div>
                                        <label class="required" for="id_source_code">Source code:</label>
        
                                        <textarea name="source_code" cols="40" rows="10" class="vLargeTextField" required="" id="id_source_code"></textarea>
                                    </div>
        
                                </div> -->

                    <div class="form-row field-question">


                        <div>


                            <label class="required" for="id_stdin">Question:</label>

                            <textarea name="stdin" cols="40" rows="10" class="vLargeTextField" required="" id="id_question"></textarea>



                        </div>

                    </div>

                    <div class="form-row field-stdin">


                        <div>


                            <label class="required" for="id_stdin">Stdin:</label>

                            <textarea name="stdin" cols="40" rows="10" class="vLargeTextField" required="" id="id_stdin"></textarea>



                        </div>

                    </div>

                    <div class="form-row field-stdout">


                        <div>


                            <label class="required" for="id_stdout">Stdout:</label>

                            <textarea name="stdout" cols="40" rows="10" class="vLargeTextField" required="" id="id_stdout"></textarea>



                        </div>

                    </div>

                    <div class="form-row field-language_id">


                        <div>


                            <label class="required" for="id_language_id">Language id:</label>

                            <textarea name="language_id" cols="40" rows="10" class="vLargeTextField" required="" id="id_language_id">4</textarea>



                        </div>

                    </div>

                    <!-- <div class="form-row field-hw_name">
        
        
                                    <div>
        
        
                                        <label class="required" for="id_file_name">hw name:</label>
        
                                        <textarea name="hw_name" cols="40" rows="10" class="vLargeTextField" required="" id="id_hw_name"></textarea>
        
        
                                    </div>
        
                                </div> -->


                </fieldset>













                <div class="submit-row">
                    <button id="save" type="submit" value="Save" class="default" name="_save" align="left">
                        save</button>
                </div>


            </div>

        </div>


        <br class="clear">
    </div>
    <script>
        document.getElementById("save").addEventListener("click", save);

        function save() {

            var question = document.getElementById("id_question").value;
            var language_id = document.getElementById("id_language_id").value;
            var stdin = document.getElementById("id_stdin").value;
            var stdout = document.getElementById("id_stdout").value;
            var data = {
                question: question,
                language_id: language_id,
                stdin: stdin,
                stdout: stdout
            };



            jQuery.ajax({
                url: `{{twk_url}}/publish_hw/`,
                type: "POST",
                async: true,
                headers: {
                    "Accept": "application/json",
                    //  'X-CSRFToken': $('meta[name="token"]').attr('ontent')
                },
                data: JSON.stringify(data),
                success: function (data, textStatus, jqXHR) {
                    alert("upload successfully");
                    window.location.replace("{{twk_url}}/templates/ide.html");

                },
                error: function () {
                    console.log("fail")
                }
            });
        }
    </script>
</body> {% endblock %}
{% endif %}
{% endif %}


</html>

twk_backend/templates/user_page.html
<html>
    <head>
            <meta charset="utf-8" />
            <meta http-equiv="X-UA-Compatible" content="IE=edge">       
            <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>           
            <script>
                $(document).ready(function() {
                  $.ajax({
                      url: '{{twk_url}}/publish_hw',
                      type: 'GET',
                      async: true,
                      success: function(data) {
                        console.log(data[0]);
                        $(".container").text(JSON.stringify(data[0]));
                      }
                  })
                });
            </script>
    </head>
    <body>
        <div class="container">
            {{ data }}
        </div>

    </body>   
</html>